version: "3.3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "touchbell_dev"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "root"
      # You can use whatever password you like
      MYSQL_PASSWORD: "reinda8426"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "reinda8426"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "127.0.0.1:3306:3306"
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
    my-db:
