# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9a64ed9fcb46543ac2282480d1d391796d5fae1826760d84720f82910d90e8132cf3d937d8bb6f96df9f99e54730d7c742f556dcf1ceeabf3127ca963dbd341

test:
  secret_key_base: 66bdb7c240e95df34762bb5e4097a21a3d09d6341a9cc147f35d9d404b79dcab7c1967df825f0010420d0bad2936c131a1e7481247734c9326740c8b9b38dda2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
